# Generated by Django 5.0.3 on 2024-08-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_pdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.FileField(upload_to=''),
        ),
    ]
