# Generated by Django 5.1 on 2024-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=220)),
                ('link', models.CharField(max_length=20)),
            ],
        ),
    ]
