# Generated by Django 5.1 on 2024-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('line', models.CharField(max_length=100)),
            ],
        ),
    ]
