# Generated by Django 5.1 on 2024-08-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_blog_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_list',
            old_name='line',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='blog_list',
            old_name='image',
            new_name='photo',
        ),
    ]
