# Generated by Django 5.1 on 2024-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('marks1', models.IntegerField(max_length=10)),
                ('marks2', models.IntegerField(max_length=10)),
                ('marks3', models.IntegerField(max_length=10)),
                ('marks4', models.IntegerField(max_length=10)),
                ('marks5', models.IntegerField(max_length=10)),
                ('total', models.IntegerField(max_length=20)),
                ('percentage', models.IntegerField(max_length=20)),
                ('grade', models.TextField(max_length=6)),
                ('min_marks', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
